apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-standard 